/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-east-2",
//     "aws_cognito_identity_pool_id": "us-east-2:690067865614:userpool/us-east-2_4zbmHhu2e",
//     "aws_cognito_region": "us-east-2",
//     "aws_user_pools_id": "us-east-2_4zbmHhu2e",
//     "aws_user_pools_web_client_id": "t7vokk31m07rigku5i4t6nlcn",
//     "oauth": {}
// };
//
//
// export default awsmobile;

